### PR TITLE
Added automatic documentation with the sphinx package

### PR DESCRIPTION
**Pull request by eugenioLR**
All the necessary files are stored in the docs folder.

To see the documentation as a web page build it by going to the docs folder and using the ```make html``` command.

You might need to install some packages like sphinx and pydata_sphinx_theme.

You are also welcome to change the theme of the page to anything you want.

Check it out and tell me what you think.

### CODE REVIEW

**Comment by vgarciasc** [comment]
Loved it!! Changed the theme to another one that I thought looked better, but then reverted back because I changed my mind.

How should we deploy this? I know people use "readthedocs" to do something similar, but I don't know if we need to commit the _build files or what.

**Comment by eugenioLR** [comment]
It's not very hard to do. The website has a tutorial on how to do it https://docs.readthedocs.io/en/stable/tutorial/index.html. To summarize, you need to add a .readthedocs.yaml to the repository. Then, you make an account on readthedocs.org, choose a repository on github and a branch, and it should build the webpage.

I can add the configuration file and you  can upload the page.

**Comment by vgarciasc** [comment]
It's working! Check it out:
https://hundred-hammers.readthedocs.io/en/latest/
Hooray! Closing this now :)

**Comment by vgarciasc** [comment]
Accidentally pushed "close" instead of "merge". Sorry.

**Pull request merged**
